### PR TITLE
[WIP- 2 tests failing] Update for geo_types 0.4

### PR DESCRIPTION
**Pull request by boydjohnson**
I am unsure of why the two tests are failing and am looking for another set of eyes on this.

I would like to use this crate and would like to use an up-to-date geo crate, so I updated this crate to use the latest geo_types.

### CODE REVIEW

**Comment by boydjohnson** [comment]
plot

These are the rectangles that are having their difference and union found in the tests.

**Comment by boydjohnson** [comment]
My latest thought is that the tests might be wrong. There should be 12 points in the polygon that represents the Union, and 2 polygons in the multipolygon that represents the difference.

**Comment by grokse** [comment]
I agree, the test looks wrong.  I'm curious why upgrading the geo-types crate fixed those two cases.

**Comment by grokse** [comment]
There was a change in geo-types to automatically close linear rings in Polygon::new.  The tests on master will fail in the exact same way if you manually close the rings.

**Pull request merged**
